"use client";

import React, { useState } from "react";
import { jsPDF } from "jspdf";
import { Download, Loader2, CheckCircle } from "lucide-react";
import { Button } from "./ui/button";

interface CategoryScore {
  name: string;
  score: number;
  comment: string;
}

interface DownloadReportButtonProps {
  interviewRole: string;
  totalScore: number;
  finalAssessment: string;
  strengths: string[];
  improvements: string[];
  categoryScores: CategoryScore[];
  userName: string;
}

const DownloadReportButton = ({
  interviewRole,
  totalScore,
  finalAssessment,
  strengths,
  improvements,
  categoryScores,
  userName,
}: DownloadReportButtonProps) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);

  const generatePDF = async () => {
    setIsGenerating(true);
    const doc = new jsPDF();
    const margin = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    let cursorY = 20;

    // Header
    doc.setFillColor(0, 102, 255); // Primary Blue
    doc.rect(0, 0, pageWidth, 40, "F");
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("INTERACT AI", margin, 20);
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Performance Evaluation Report", margin, 32);
    
    doc.text(new Date().toLocaleDateString(), pageWidth - margin - 20, 20);

    cursorY = 55;

    // Candidate Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(`Candidate: ${userName}`, margin, cursorY);
    cursorY += 10;
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`Role: ${interviewRole} Interview`, margin, cursorY);
    cursorY += 20;

    // Overall Score Circle (Mock)
    doc.setDrawColor(0, 102, 255);
    doc.setLineWidth(1);
    doc.circle(margin + 15, cursorY + 15, 15);
    
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(`${totalScore}`, margin + 11, cursorY + 16);
    
    doc.setFontSize(12);
    doc.text("Overall Readiness Score", margin + 40, cursorY + 16);
    cursorY += 40;

    // Expert Insights
    doc.setFontSize(14);
    doc.text("Expert Insights:", margin, cursorY);
    cursorY += 8;
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    const splitAssessment = doc.splitTextToSize(finalAssessment, pageWidth - (margin * 2));
    doc.text(splitAssessment, margin, cursorY);
    cursorY += (splitAssessment.length * 5) + 15;

    // Strengths
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(34, 197, 94); // Green
    doc.text("Key Strengths:", margin, cursorY);
    cursorY += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    strengths.slice(0, 5).forEach((s) => {
      doc.text(`• ${s}`, margin + 5, cursorY);
      cursorY += 6;
    });
    cursorY += 10;

    // Improvements
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(249, 115, 22); // Orange
    doc.text("Areas for Growth:", margin, cursorY);
    cursorY += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    improvements.slice(0, 5).forEach((item) => {
      doc.text(`• ${item}`, margin + 5, cursorY);
      cursorY += 6;
    });

    // Skill Breakdown Table (Simplified)
    cursorY += 15;
    doc.setFont("helvetica", "bold");
    doc.text("Skill Breakdown:", margin, cursorY);
    cursorY += 8;
    
    doc.setFont("helvetica", "normal");
    categoryScores.forEach((cat) => {
      if (cursorY > 270) {
        doc.addPage();
        cursorY = 20;
      }
      doc.text(`${cat.name}:`, margin + 5, cursorY);
      doc.text(`${cat.score}/100`, pageWidth - margin - 20, cursorY);
      
      // Progress bar mockup
      doc.setDrawColor(200, 200, 200);
      doc.line(margin + 5, cursorY + 2, pageWidth - margin, cursorY + 2);
      doc.setDrawColor(0, 102, 255);
      doc.setLineWidth(2);
      const barPadding = 25;
      const barLength = (pageWidth - (margin * 2) - barPadding) * (cat.score / 100);
      doc.line(margin + 5, cursorY + 2, margin + 5 + barLength, cursorY + 2);
      
      cursorY += 12;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by InteractAI - Team Invincibles", pageWidth / 2, 285, { align: "center" });

    doc.save(`${userName}_Interview_Report.pdf`);
    
    setIsGenerating(false);
    setIsSuccess(true);
    setTimeout(() => setIsSuccess(false), 3000);
  };

  return (
    <Button 
      onClick={generatePDF} 
      disabled={isGenerating}
      className={`relative overflow-hidden transition-all duration-300 min-w-[200px] ${
        isSuccess ? "bg-green-500 hover:bg-green-600 shadow-lg shadow-green-500/20" : "btn-gradient"
      }`}
    >
      <div className="flex items-center justify-center gap-2">
        {isGenerating ? (
          <>
            <Loader2 className="w-4 h-4 animate-spin" />
            <span>Analyzing...</span>
          </>
        ) : isSuccess ? (
          <>
            <CheckCircle className="w-4 h-4" />
            <span>Report Saved</span>
          </>
        ) : (
          <>
            <Download className="w-4 h-4" />
            <span>Download PDF Report</span>
          </>
        )}
      </div>
    </Button>
  );
};

export default DownloadReportButton;
